services:
  - type: web
    name: springboot-web-hosting
    env: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    plan: free
    envVars:
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk
